apiVersion: v2
name: helm-with-dependencies
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: bitnami/mediawiki
  version: 14.3.15
  repository: https://charts.bitnami.com/bitnami
- name: k8s-at-home/homer
  version: 8.0.2
  repository: https://k8s-at-home.com/charts
